FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev --ignore-scripts

COPY . .

EXPOSE 3000

CMD ["node", "-r", "dotenv/config", "src/backend/VincularGatlingConBD.js"]
