# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    
    env:
      NODE_VER: 24.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VER }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx eslint src/
    - run: npx jest 
    
  test:

      runs-on: ubuntu-latest

      env:
        NODE_VER: 24.x

      steps:
      - name: checkout codecov
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ env.NODE_VER }}
            cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with: 
            token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Convertir reporte de Jest en PDF 
        run: npx html-pdf-cli coverage/lcov-report/index.html reporte-cobertura.pdf

      - name: Guardar PDF como artefacto en github
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura-pdf
          path: reporte-cobertura.pdf